services:
  quiz-app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: teachers_day_quiz

    restart: unless-stopped

    volumes:
      - ./data:/app/data

    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0

    networks:
      - quiz
      - monitoring

    labels:
      kuma.monitor: "true"
      kuma.url: "http://teachers_day_quiz:3000"

networks:
  quiz:
    driver: bridge

  monitoring:
    external: true
